### ISSUE TITLE
搜图失败 | IndexError: list index out of range

### ISSUE THREAD

**Issue by Mashiro69** [NekoAria/YetAnotherPicSearch#100]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

❯ python --version
Python 3.11.2

❯ pip list
Package                               Version
------------------------------------- --------
nonebot2                              2.0.0
nonebot-plugin-gocqhttp               0.6.10
picimagesearch                        3.9.3
yetanotherpicsearch                   1.9.3

❯ uname -a
Linux AWS 6.1.0-10-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

### 如何复现

搜索任何图片都稳定复现

### 实际行为

07-11 19:45:17 [ERROR] YetAnotherPicSearch | 该图 [https://gchat.qpic.cn/gchatpic_new/0/0-0-87E91D5B3B0ACA30CC310328E4546E34/0] 搜图失败
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 272, in handle_image_search
    await image_search(
> File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 106, in image_search
    await send_result_message(bot, event, result, index)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 194, in send_result_message
    and event.user_id == int(list(config.superusers)[0])
IndexError: list index out of range
07-11 19:45:17 [INFO] nonebot | Matcher(type='message', module=YetAnotherPicSearch) running complete
07-11 19:45:17 [ERROR] nonebot | Running Matcher(type='message', module=YetAnotherPicSearch) failed.
Traceback (most recent call last):
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 106, in image_search
    await send_result_message(bot, event, result, index)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 194, in send_result_message
    and event.user_id == int(list(config.superusers)[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 272, in handle_image_search
    await image_search(
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 113, in image_search
    await send_result_message(bot, event, [f"该图搜图失败\nE: {repr(e)}"], index)
  File "/root/NoneBot/.venv/lib/python3.11/site-packages/YetAnotherPicSearch/__init__.py", line 194, in send_result_message
    and event.user_id == int(list(config.superusers)[0])
IndexError: list index out of range

**Comment by NekoAria** [comment]
你没有配置 superusers
