### ISSUE TITLE
你好启动后报加载错误。ImportError: cannot import name 'BaseConfig' from 'nonebot.config' (D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\config.py)

### ISSUE THREAD

**Issue by lintonxue00** [NekoAria/YetAnotherPicSearch#124]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

。

### 列出安装的 Python 包

。

### 如何复现

安装这个插件然后报错

### 期望行为

正常启动

### 实际行为

02-15 15:19:07 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\USER451533\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\YetAnotherPicSearch\__init__.py", line 23, in <module>
    from .ascii2d import ascii2d_search
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\YetAnotherPicSearch\ascii2d.py", line 7, in <module>
    from .config import config
  File "D:\yunzai\nonebot\qq2\.venv\lib\site-packages\YetAnotherPicSearch\config.py", line 4, in <module>
    from nonebot.config import BaseConfig
ImportError: cannot import name 'BaseConfig' from 'nonebot.config' (D:\yunzai\nonebot\qq2\.venv\lib\site-packages\nonebot\config.py)

**Comment by NekoAria** [comment]
你安装了最新的 nonebot 2.2.0 ？
是的话自己解决：https://nonebot.dev/docs/appendices/config

再说，你连 issue 模板里要求提供的必要信息都不写，我怎么知道是哪里的问题。

**Comment by SEAFHMC** [comment]
你好 我pydantic的版本降到1.10.14仍会出现这个报错】

**Comment by NekoAria** [comment]
> 你好 我pydantic的版本降到1.10.14仍会出现这个报错】

这个PR 合并后应该不需要降级了吧：#126 
你问问 @lgc2333 。

**Comment by lgc2333** [comment]
检查看看你yaps的版本？我这边没啥问题啊

**Comment by SEAFHMC** [comment]
yaps版本:1.9.4
nonebot2版本:2.2.1
pydantic版本:1.10.14

**Comment by lgc2333** [comment]
更新到1.9.6

**Comment by SEAFHMC** [comment]
![Screenshot_2024-03-25-20-11-57-88_61c78dc80ee02b53007c815fefe993e3](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/39eb9709-c3cd-460d-85c7-c33f71e15b00)
![Screenshot_2024-03-25-20-14-38-23_61c78dc80ee02b53007c815fefe993e3](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/6ce7dd0f-493d-4140-be7f-571bec8ba2d6)
pip install -U没找到1.9.6的于是尝试源码安装了，显示依赖冲突，于是我修改了pypoject.toml里lxml和httpx的版本要求与picimagesearch一致，安装成功了。
但是现在在配置了SAUCENAO_KEY的情况下机器人回复无法使用SAUCENAO并且没有返回搜图结果。服务器在墙外应该不是梯子的问题。

**Comment by lgc2333** [comment]
建议新开个issue，再带上Bot的回复截图和你的env对应配置（可以部分打码）
