### ISSUE TITLE
Failed to import "YetAnotherPicSearch“

### ISSUE THREAD

**Issue by CIRNO9X** [NekoAria/YetAnotherPicSearch#125]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch:1.9.4
PicImageSearch:3.9.7
没用go-cqhttp，用的shamrock
nonebot:2.2.0
python:3.10.12
操作系统:ubuntu 2204

### 如何复现

使用pip命令安装插件后运行，报错Failed to import "YetAnotherPicSearch“
更新nonebot到最新版后仍然失败，降级 Pydantic至v1版本也不行
降级nonebot到2.0.0和2.1.3依旧报错

### 实际行为

02-20 11:27:22 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/__init__.py", line 23, in <module>
    from .ascii2d import ascii2d_search
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/ascii2d.py", line 7, in <module>
    from .config import config
  File "/root/CirnoBot/.venv/lib/python3.10/site-packages/YetAnotherPicSearch/config.py", line 4, in <module>
    from nonebot.config import BaseConfig
ImportError: cannot import name 'BaseConfig' from 'nonebot.config' (/root/CirnoBot/.venv/lib/python3.10/site-packages/nonebot/config.py)

**Comment by NekoAria** [comment]
请你先参照这个进行尝试：https://nonebot.dev/docs/appendices/config

**Comment by lgc2333** [comment]
这是nonebot 2.0.0的问题，插件开发者需要自行从pydantic导入BaseModel
