### ISSUE TITLE
在没有搜图结果的时候不能正确返回搜图失败

### ISSUE THREAD

**Issue by TheValkyrja** [NekoAria/YetAnotherPicSearch#13]
不清楚这是我环境出现了问题还是是beta4有什么不兼容..？

nb内错信息：

>07-19 06:49:56 [ERROR] nonebot | Running matcher <Matcher from YetAnotherPicSearch, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/YetAnotherPicSearch/__init__.py", line 209, in handle_image_search
    await send_result_message(
  File "/usr/local/lib/python3.10/dist-packages/YetAnotherPicSearch/__init__.py", line 149, in send_result_message
    await send_forward_msg(bot, event, msg_list)
  File "/usr/local/lib/python3.10/dist-packages/YetAnotherPicSearch/__init__.py", line 177, in send_forward_msg
    messages=[
  File "/usr/local/lib/python3.10/dist-packages/YetAnotherPicSearch/__init__.py", line 181, in <listcomp>
    "name": config.nickname[0] if config.nickname else "\u200b",
TypeError: 'set' object is not subscriptable

**Comment by NekoAria** [comment]
我的问题，没注意这是个 set ，不能直接用下标取。
