### ISSUE TITLE
E: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

### ISSUE THREAD

**Issue by SakuraXiaoWen** [NekoAria/YetAnotherPicSearch#25]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

插件版本最新的
go-cqhttp：v1.0.0-rc3
nonebot：beta5
python：3.9.13
系统：centos 7.9

### 如何复现

搜图后返回这个错误

### 实际行为

08-12 00:53:57 [ERROR] plugins | ❌️ 该图 [https://gchat.qpic.cn/gchatpic_new/0/0-0-167AE7DBAB719A311D1E371DCC52434D/0] 搜图失败
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/python3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/python3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/python3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/bot/nonebot/plugins/YetAnotherPicSearch/__init__.py", line 220, in handle_image_search
    await image_search(value, mode, purge, _cache, client),
> File "/bot/nonebot/plugins/YetAnotherPicSearch/__init__.py", line 87, in image_search
    async for attempt in AsyncRetrying(
  File "/usr/local/python3.9/lib/python3.9/site-packages/tenacity/_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/local/python3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/usr/local/python3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/python3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/python3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/bot/nonebot/plugins/YetAnotherPicSearch/__init__.py", line 98, in image_search
    result = await saucenao_search(url, mode, client, hide_img)
  File "/bot/nonebot/plugins/YetAnotherPicSearch/saucenao.py", line 38, in saucenao_search
    res = await saucenao.search(url)
  File "/usr/local/python3.9/lib/python3.9/site-packages/PicImageSearch/saucenao.py", line 114, in search
    resp_json = json_loads(resp_text)
  File "/usr/local/python3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![QQ截图20220812003310](https://user-images.githubusercontent.com/46924591/184192643-1d122d82-e18c-49a5-b787-5611bf341cff.png)

**Comment by NekoAria** [comment]
是否配置了 `SAUCENAO_API_KEY` ？

**Comment by SakuraXiaoWen** [comment]
配置了
![QQ截图20220812012717](https://user-images.githubusercontent.com/46924591/184195903-9c7e2217-aa78-434a-b0c7-ee85e09856f9.png)

**Comment by NekoAria** [comment]
有尝试过其他图片吗？
还是只有该图片会触发？
能访问 saucenao.com 吗？

**Comment by SakuraXiaoWen** [comment]
其他图片也是这个报错
能够正常访问
![Screenshot_2022-08-12-01-37-05-206_com tencent mo](https://user-images.githubusercontent.com/46924591/184198027-d10c8419-5d80-4ec3-95d9-66373a9c4290.jpg)
![Screenshot_2022-08-12-01-37-01-179_com tencent mo](https://user-images.githubusercontent.com/46924591/184198040-d4e61ba9-fde2-4e16-8b31-72cbdb04cf7d.jpg)
![QQ截图20220812013831](https://user-images.githubusercontent.com/46924591/184198055-706c1bfa-c51f-4450-b0e7-78c6c9760488.png)

**Comment by NekoAria** [comment]
看样子是触发 cf 盾了。。

**Comment by SakuraXiaoWen** [comment]
那有什么解决办法吗，大佬

**Comment by NekoAria** [comment]
你有代理的话，先配置一下代理吧，我明天再看看能不能修

**Comment by SakuraXiaoWen** [comment]
好的

**Comment by NekoAria** [comment]
如果你的服务器是在国内的，还是上代理解决吧，就算能直连 saucenao.com ，其他相关图站几乎都被墙了。
