### ISSUE TITLE
插件与`playwright`不兼容

### ISSUE THREAD

**Issue by lgc2333** [NekoAria/YetAnotherPicSearch#32]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

gocq rc3
nb2 b5
py 3.10.3

### 如何复现

安装`nonebot-plugin-htmlrender`并加载，启动application时报错

### 实际行为

如果需要更多内容请直接在底下回复

初步判断是`asyncio.set_event_loop_policy`的问题  
把这部分代码注释掉即可正常运行

**Comment by lgc2333** [comment]
操作系统是 win server 2019

**Comment by NekoAria** [comment]
能把启动后报错的日志发一下吗？

**Comment by lgc2333** [comment]
```py
(env) C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta>nb run
08-29 18:53:54 [SUCCESS] nonebot | NoneBot is initializing...
08-29 18:53:54 [INFO] nonebot | Current Env: prod
08-29 18:53:55 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
08-29 18:53:55 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_maze"
08-29 18:53:55 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_code"
08-29 18:53:56 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_localstore"
08-29 18:53:56 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_datastore"
08-29 18:53:58 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_cchess"
08-29 18:53:59 [SUCCESS] nonebot | Succeeded to import "genshinuid_roleinfo"
08-29 18:53:59 [SUCCESS] nonebot | Succeeded to import "genshinuid_adv"
08-29 18:53:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
08-29 18:53:59 [SUCCESS] nonebot | Succeeded to import "genshinuid_eventlist"
08-29 18:53:59 [SUCCESS] nonebot | Succeeded to import "genshinuid_etcimg"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "genshinuid_enka"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "genshinuid_abyss"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "genshinuid_wikitext"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "genshinuid_config"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "config"
08-29 18:54:00 [SUCCESS] nonebot | Succeeded to import "version"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_signin"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_collection"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_check"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_gachalog"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_resin"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_user"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_help"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_meta"
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_resource"
08-29 18:54:01 [INFO] src | [资源文件下载] 正在检查与下载缺失的资源文件，可能需要较长时间，请稍等
08-29 18:54:01 [SUCCESS] nonebot | Succeeded to import "genshinuid_note"
08-29 18:54:02 [SUCCESS] nonebot | Succeeded to import "genshinuid_guide"
08-29 18:54:02 [SUCCESS] nonebot | Succeeded to import "genshinuid_mhybbscoin"
08-29 18:54:03 [INFO] src | [minigg.icu]数据库[角色名片]中存在54个内容!
08-29 18:54:03 [INFO] src | [minigg.icu]数据库[角色名片]无需下载!
08-29 18:54:04 [INFO] src | [minigg.icu]数据库[角色侧视图]中存在54个内容!
08-29 18:54:04 [INFO] src | [minigg.icu]数据库[角色侧视图]无需下载!
08-29 18:54:04 [SUCCESS] nonebot | Succeeded to import "genshinuid_map"
08-29 18:54:04 [SUCCESS] nonebot | Succeeded to import "GenshinUID"
08-29 18:54:04 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_hammer_nbnhhsh"
08-29 18:54:04 [INFO] src | [minigg.icu]数据库[角色半身照]中存在55个内容!
08-29 18:54:04 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_heweather"
08-29 18:54:04 [INFO] src | [minigg.icu]数据库[角色半身照]无需下载!
08-29 18:54:05 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_logo"
08-29 18:54:05 [INFO] src | [minigg.icu]数据库[角色头像]中存在56个内容!
08-29 18:54:05 [INFO] src | [minigg.icu]数据库[角色头像]无需下载!
08-29 18:54:05 [SUCCESS] nonebot | Succeeded to import "domain_whitelist"
08-29 18:54:06 [SUCCESS] nonebot | Succeeded to import "YetAnotherPicSearch"
08-29 18:54:06 [INFO] src | [minigg.icu]数据库[角色立绘]中存在54个内容!
C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
08-29 18:54:06 [INFO] src | [minigg.icu]数据库[角色立绘]无需下载!
08-29 18:54:06 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_PicMenu"
08-29 18:54:06 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_asoulcnki"
08-29 18:54:06 [SUCCESS] nonebot | Succeeded to import "Genshin_Impact_bot"
08-29 18:54:07 [INFO] src | [minigg.icu]数据库[图标]中存在661个内容!
08-29 18:54:07 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_youthstudy"
08-29 18:54:07 [INFO] haruka_bot | 检查 Chromium 更新
08-29 18:54:07 [INFO] src | [minigg.icu]数据库[图标]无需下载!
08-29 18:54:08 [INFO] src | [minigg.icu]数据库[圣遗物]中存在190个内容!
08-29 18:54:08 [INFO] haruka_bot | 检查 Playwright 依赖
08-29 18:54:08 [INFO] src | [minigg.icu]数据库[圣遗物]无需下载!
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Connection.run() done, defined at C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_connection.py:212> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\haruka_bot\utils\__init__.py", line 128, in on_startup
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_connection.py", line 219, in run
    await self._transport.connect()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 139, in connect
    raise exc
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
08-29 18:54:08 [ERROR] nonebot | Failed to import "haruka_bot"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\haruka_bot\utils\__init__.py", line 128, in on_startup
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\haruka_bot\__init__.py", line 11, in <module>
    on_startup()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\haruka_bot\utils\__init__.py", line 134, in on_startup
    asyncio.run(check_playwright_env())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\haruka_bot\utils\browser.py", line 143, in check_playwright_env
    raise ImportError(
ImportError: 加载失败，Playwright 依赖不全，解决方法：https://haruka-bot.sk415.icu/faq.html#playwright-依赖不全
08-29 18:54:08 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_bawiki"
08-29 18:54:08 [INFO] src | [minigg.icu]数据库[武器]中存在142个内容!
08-29 18:54:08 [INFO] src | [minigg.icu]数据库[武器]无需下载!
08-29 18:54:08 [INFO] src | [资源文件下载] 全部资源下载完成!
08-29 18:54:09 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_imageutils"
08-29 18:54:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_memes"
08-29 18:54:11 [WARNING] nonebot | Duplicated prefix rule "停止游戏"
08-29 18:54:11 [WARNING] nonebot | Duplicated prefix rule "结束游戏"
08-29 18:54:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_minesweeper"
08-29 18:54:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_color"
08-29 18:54:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_analysis_bilibili"
08-29 18:54:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_petpet"
08-29 18:54:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_abstract"
08-29 18:54:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_withdraw"
08-29 18:54:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_emojimix"
08-29 18:54:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_guild_patch"
08-29 18:54:16 [SUCCESS] nonebot | Running NoneBot...
08-29 18:54:16 [INFO] uvicorn | Started server process [25528]
08-29 18:54:16 [INFO] uvicorn | Waiting for application startup.
Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Connection.run() done, defined at C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_connection.py:212> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_connection.py", line 219, in run
    await self._transport.connect()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 139, in connect
    raise exc
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
08-29 18:54:16 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 59, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 36, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_connection.py", line 219, in run
    await self._transport.connect()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 139, in connect
    raise exc
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

08-29 18:54:16 [ERROR] uvicorn | Application startup failed. Exiting.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000205C12B0EE0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/187185982-65fd60ee-222e-4408-905c-ba630909eb07.png)
此处修改后即可正常运行

**Comment by NekoAria** [comment]
> ![image](https://user-images.githubusercontent.com/59048777/187185982-65fd60ee-222e-4408-905c-ba630909eb07.png)
> 此处修改后即可正常运行

那搜图能正常使用吗？我就是因为 #30 才加的这段代码。
万恶的 Windows （

**Comment by lgc2333** [comment]
> > ![image](https://user-images.githubusercontent.com/59048777/187185982-65fd60ee-222e-4408-905c-ba630909eb07.png)
> > 此处修改后即可正常运行
> 
> 那搜图能正常使用吗？我就是因为 #30 才加的这段代码。 万恶的 Windows （

修改后能用，不改nb都启动不了

aiohttp版本为3.8.1

**Comment by lgc2333** [comment]
有配置代理（clash `http://127.0.0.1:10809`）2022年8月29日 下午7:29，Neko Aria ***@***.***>写道：









此处修改后即可正常运行



那搜图能正常使用吗？我就是因为 #30 才加的这段代码。 万恶的 Windows （



修改后能用，不改nb都启动不了

aiohttp版本为3.8.1



有配置代理吗？ aiohttp 在 Windows 上走代理发送 HTTPS 协议请求的时候就需要这个 WindowsSelectorEventLoopPolicy 。

主要是这个逻辑不搞清楚没法改啊（

**Comment by NekoAria** [comment]
> 有配置代理（clash `[http://127.0.0.1:10809`）2022年8月29日](http://127.0.0.1:10809%60%EF%BC%892022%E5%B9%B48%E6%9C%8829%E6%97%A5) 下午7:29，Neko Aria ***@***.***>写道： 此处修改后即可正常运行 那搜图能正常使用吗？我就是因为 #30 才加的这段代码。 万恶的 Windows （ 修改后能用，不改nb都启动不了 aiohttp版本为3.8.1 有配置代理吗？ aiohttp 在 Windows 上走代理发送 HTTPS 协议请求的时候就需要这个 WindowsSelectorEventLoopPolicy 。 主要是这个逻辑不搞清楚没法改啊（ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

那看样子和具体的 Windows 版本也有关系，实际上我 Windows 10 好像并不需要这个 WindowsSelectorEventLoopPolicy 。
麻烦你把下面这段代码的执行结果贴一下：

```Python
import platform
import sys

print(platform.platform())
print(sys.getwindowsversion())
```

**Comment by lgc2333** [comment]
Microsoft Windows [版本 10.0.17763.2330]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>py
Python 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>>
>>> import sys
>>>
>>>
>>>
>>> print(platform.platform())
Windows-10-10.0.17763-SP0
>>>
>>> print(sys.getwindowsversion())
sys.getwindowsversion(major=10, minor=0, build=17763, platform=2, service_pack='')
>>>

**Comment by lgc2333** [comment]
有需要可以qq私聊我在我的云机上debug，已配置好pycharm环境
`3076823485`

**Comment by lgc2333** [comment]
我之前试过用aiohttp 3.7来用proxy请求过其他url，出现了和#30 一样的报错，换用httpx正常

**Comment by NekoAria** [comment]
先注释掉那段逻辑了，如果之后再遇到再说，感谢反馈。
