### ISSUE TITLE
该图识图失败 E: ValueError('url or file is required')

### ISSUE THREAD

**Issue by Nenot233** [NekoAria/YetAnotherPicSearch#44]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

真寻的框架
YetAnotherPicSearch、go-cqhttp都是最新版本
nonebot b5
Python3.9

### 列出安装的 Python 包

absl-py==1.2.0
addict==2.4.0
anyio==3.6.1
appdirs==1.4.4
arrow==1.2.2
asgiref==3.5.2
audioread==2.1.9
basicsr==1.4.1
bbcode==1.1.0
CacheControl==0.12.11
cachetools==5.2.0
cachy==0.3.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
cleo==0.8.1
click==8.1.3
clikit==0.6.2
colorama==0.4.5
crashtest==0.3.1
curses @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python39/Scripts/curses-2.2.1%2Butf8-cp39-cp39-win_amd64.whl
cycler==0.11.0
decorator==5.1.1
distlib==0.3.5
facexlib==0.2.4
fastapi==0.78.0
filelock==3.7.1
filterpy==1.4.5
fonttools==4.34.4
future==0.18.2
gfpgan==1.3.4
google-auth==2.10.0
google-auth-oauthlib==0.4.6
grpcio==1.47.0
h11==0.12.0
html5lib==1.1
httpcore==0.15.0
httptools==0.4.0
httpx==0.23.0
idna==3.3
imageio==2.20.0
importlib-metadata==4.12.0
inflect==5.6.2
joblib==1.1.0
keyring==23.7.0
kiwisolver==1.4.4
langid==1.1.6
librosa==0.9.2
llvmlite==0.38.1
lmdb==1.3.0
lockfile==0.12.2
loguru==0.6.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
mockingbirdforuse==0.2.3
msgpack==1.0.4
multidict==6.0.2
networkx==2.8.5
nonebot-plugin-imageutils==0.1.7
nonebot2==2.0.0b4
numba==0.55.2
numpy==1.20.3
oauthlib==3.2.0
opencv-python==4.6.0.66
opencv-python-headless==4.6.0.66
packaging==20.9
pastel==0.2.1
pexpect==4.8.0
Pillow==9.2.0
pkginfo==1.8.3
platformdirs==2.5.2
poetry==1.1.14
poetry-core==1.0.8
pooch==1.6.0
protobuf==3.19.4
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.9.1
pygtrie==2.5.0
pylev==1.4.0
pyparsing==3.0.9
pypinyin==0.46.0
python-dateutil==2.8.2
python-dotenv==0.20.0
PyWavelets==1.3.0
pywin32-ctypes==0.2.0
PyYAML==6.0
realesrgan==0.2.5.0
requests==2.28.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
resampy==0.3.1
rfc3986==1.5.0
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.1.1
scipy==1.8.1
shellingham==1.4.0
six==1.16.0
sniffio==1.2.0
SoundFile==0.10.3.post1
starlette==0.19.1
tb-nightly==2.10.0a20220806
tenacity==8.0.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2022.8.3
tomlkit==0.11.1
torch==1.12.1
torchvision==0.13.1
tqdm==4.64.0
typing_extensions==4.3.0
Unidecode==1.3.4
urllib3==1.26.10
uvicorn==0.17.6
virtualenv==20.15.1
watchgod==0.8.2
webencodings==0.5.1
webrtcvad==2.0.10
websockets==10.3
Werkzeug==2.2.1
win32-setctime==1.1.0
yapf==0.32.0
yarl==1.7.2
zipp==3.8.1

pip list
Package                   Version
------------------------- ---------------
absl-py                   1.2.0
addict                    2.4.0
anyio                     3.6.1
appdirs                   1.4.4
arrow                     1.2.2
asgiref                   3.5.2
audioread                 2.1.9
basicsr                   1.4.1
bbcode                    1.1.0
CacheControl              0.12.11
cachetools                5.2.0
cachy                     0.3.0
certifi                   2022.6.15
cffi                      1.15.1
charset-normalizer        2.1.0
cleo                      0.8.1
click                     8.1.3
clikit                    0.6.2
colorama                  0.4.5
crashtest                 0.3.1
curses                    2.2.1+utf8
cycler                    0.11.0
decorator                 5.1.1
distlib                   0.3.5
facexlib                  0.2.4
fastapi                   0.78.0
filelock                  3.7.1
filterpy                  1.4.5
fonttools                 4.34.4
future                    0.18.2
gfpgan                    1.3.4
google-auth               2.10.0
google-auth-oauthlib      0.4.6
grpcio                    1.47.0
h11                       0.12.0
html5lib                  1.1
httpcore                  0.15.0
httptools                 0.4.0
httpx                     0.23.0
idna                      3.3
imageio                   2.20.0
importlib-metadata        4.12.0
inflect                   5.6.2
joblib                    1.1.0
keyring                   23.7.0
kiwisolver                1.4.4
langid                    1.1.6
librosa                   0.9.2
llvmlite                  0.38.1
lmdb                      1.3.0
lockfile                  0.12.2
loguru                    0.6.0
Markdown                  3.4.1
MarkupSafe                2.1.1
matplotlib                3.5.2
mockingbirdforuse         0.2.3
msgpack                   1.0.4
multidict                 6.0.2
networkx                  2.8.5
nonebot-plugin-imageutils 0.1.7
nonebot2                  2.0.0b4
numba                     0.55.2
numpy                     1.20.3
oauthlib                  3.2.0
opencv-python             4.6.0.66
opencv-python-headless    4.6.0.66
packaging                 20.9
pastel                    0.2.1
pexpect                   4.8.0
Pillow                    9.2.0
pip                       22.2.2
pkginfo                   1.8.3
platformdirs              2.5.2
poetry                    1.1.14
poetry-core               1.0.8
pooch                     1.6.0
protobuf                  3.19.4
ptyprocess                0.7.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pycparser                 2.21
pydantic                  1.9.1
pygtrie                   2.5.0
pylev                     1.4.0
pyparsing                 3.0.9
pypinyin                  0.46.0
python-dateutil           2.8.2
python-dotenv             0.20.0
PyWavelets                1.3.0
pywin32-ctypes            0.2.0
PyYAML                    6.0
realesrgan                0.2.5.0
requests                  2.28.1
requests-oauthlib         1.3.1
requests-toolbelt         0.9.1
resampy                   0.3.1
rfc3986                   1.5.0
rsa                       4.9
scikit-image              0.19.3
scikit-learn              1.1.1
scipy                     1.8.1
setuptools                58.1.0
shellingham               1.4.0
six                       1.16.0
sniffio                   1.2.0
SoundFile                 0.10.3.post1
starlette                 0.19.1
tb-nightly                2.10.0a20220806
tenacity                  8.0.1
tensorboard-data-server   0.6.1
tensorboard-plugin-wit    1.8.1
threadpoolctl             3.1.0
tifffile                  2022.8.3
tomlkit                   0.11.1
torch                     1.12.1
torchvision               0.13.1
tqdm                      4.64.0
typing_extensions         4.3.0
Unidecode                 1.3.4
urllib3                   1.26.10
uvicorn                   0.17.6
virtualenv                20.15.1
watchgod                  0.8.2
webencodings              0.5.1
webrtcvad                 2.0.10
websockets                10.3
Werkzeug                  2.2.1
wheel                     0.37.1
win32-setctime            1.1.0
yapf                      0.32.0
yarl                      1.7.2
zipp                      3.8.1

### 如何复现

识图就出现了

### 实际行为

10-13 17:20:34 [ERROR] extensive_plugin | 该图  [cq图片] 识图失败
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 265, in handle_image_search
    await image_search(value, mode, purge, _cache, client),
> File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 123, in image_search
    async for attempt in AsyncRetrying(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 134, in image_search
    result = await saucenao_search(url, mode, client, hide_img)
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\saucenao.py", line 118, in saucenao_search
    final_res.extend(await ascii2d_search(url, client, hide_img))
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\ascii2d.py", line 14, in ascii2d_search
    color_res = await ascii2d_color.search(file=file)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\PicImageSearch\ascii2d.py", line 55, in search
    raise ValueError("url or file is required")
ValueError: url or file is required

该图识图失败
E: ValueError('url or file is required')

**Comment by NekoAria** [comment]
> 该图  [cq图片] 识图失败

这报错不属于 YetAnotherPicSearch 吧。

还有你是怎么用的？能截图发来看看吗？

**Comment by Nenot233** [comment]
![Screenshot_2022-10-13-17-49-50-671_com tencent mobileqq](https://user-images.githubusercontent.com/108965579/195565877-3e8b3b22-46d8-4dc4-b6e8-67c7c9449e87.jpg)
是这样使用的，是因为和真寻的不适配么？

**Comment by NekoAria** [comment]
你重新下载过吧，看来是你的 `ascii2d.py` 文件不是最新的。

**Comment by Nenot233** [comment]
今天更新的版本，应该是最新的

**Comment by NekoAria** [comment]
> 今天更新的版本，应该是最新的

最新的这一行是 `color_res = await ascii2d_color.search(file=_file)` ：

```diff
- color_res = await ascii2d_color.search(file=file)
+ color_res = await ascii2d_color.search(file=_file)
```

上一行也是 `_file` 。

别的我也不知道哪里不是最新的，你自己检查一下吧。

**Comment by Nenot233** [comment]
10-13 19:03:53 [ERROR] extensive_plugin | 该图 [] 识图失败
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 268, in handle_image_search
    await image_search(value, mode, purge, _cache, client),
> File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 124, in image_search
    async for attempt in AsyncRetrying(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tenacity\__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\__init__.py", line 137, in image_search
    result = await saucenao_search(url, mode, client, hide_img)
  File "D:\BOT\zhenxun_bot\extensive_plugin\YetAnotherPicSearch\saucenao.py", line 60, in saucenao_search
    elif len(selected_res.ext_urls) > 1:
AttributeError: 'SauceNAOItem' object has no attribute 'ext_urls'

**Comment by NekoAria** [comment]
> 已经找到问题所在
> 需要
> pip uninstall PicImageSearch
> 再
> pip install PicImageSearch
> 就可以了，应该是版本问题，十分感谢作者！

实际上只需要 `pip install -U PicImageSearch` ，不需要卸载重装。

**Comment by Nenot233** [comment]
今天翻遍了iss里面看到过这个指令，可能是我电脑的问题使用pip install -U PicImageSearch会报错(?)
重新卸了再下载就可以了，非常感谢指导
