### ISSUE TITLE
启动报错ValueError

### ISSUE THREAD

**Issue by forchannot** [NekoAria/YetAnotherPicSearch#92]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

最新1.9.1，nb是rc4

### 列出安装的 Python 包

https://netcut.cn/yetanother

### 如何复现

启动nb

### 期望行为

正常启动

### 实际行为

```
05-26 01:02:20 [ERROR] nonebot | Failed to import "YetAnotherPicSearch"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LittlePaimon\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\YetAnotherPicSearch\__init__.py", line 30, in <module>
    from .saucenao import saucenao_search
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\YetAnotherPicSearch\saucenao.py", line 11, in <module>
    from .nhentai import nhentai_title_search
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\YetAnotherPicSearch\nhentai.py", line 25, in <module>
    NHENTAI_COOKIES = parse_cookies(config.nhentai_cookies)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\YetAnotherPicSearch\utils.py", line 156, in parse_cookies
    key, value = line.strip().split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
其中，配置的nhentaick为
```
nhentai_cookies="cf_clearance=xxx; xxxx; sessionid=xxxx; sessionid=xxxx"
```
已脱敏

**Comment by forchannot** [comment]
没事了，ck复制出了点毛病(
